<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])

array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("1D Array:")
print(array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)

print("\n2D Array:")
print(array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64
