<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

try:
    # Get number of elements
    n = int(input("Enter how many numbers you want to generate: "))

    if n <= 0:
        print("Please enter a positive number.")
    else:
        # Generate random numbers
        arr = np.random.randint(10, 101, n)

        print("\nGenerated Array:")
        print(arr)

        # Display statistics
        print("\nMean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum:", np.min(arr))
        print("Maximum:", np.max(arr))

        # Reshape into 2D if possible
        rows = int(np.sqrt(n))

        while rows > 1:
            if n % rows == 0:
                cols = n // rows
                matrix = arr.reshape(rows, cols)

                print("\n2D Array:")
                print(matrix)

                print("\nRow-wise Sum:")
                print(np.sum(matrix, axis=1))
                break
            rows -= 1
        else:
            print("\nCannot reshape into a 2D array.")

except ValueError:
    print("Invalid input! Please enter an integer.")
except Exception as e:
    print("Error:", e)

Enter how many numbers you want to generate: 12

Generated Array:
[66 63 75 10 46 35 50 36 28 26 44 93]

Mean: 47.666666666666664
Median: 45.0
Standard Deviation: 22.29848026709942
Minimum: 10
Maximum: 93

2D Array:
[[66 63 75 10]
 [46 35 50 36]
 [28 26 44 93]]

Row-wise Sum:
[214 167 191]
