<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

array1 = np.zeros(8)

array2 = np.ones((4, 4))

array3 = np.zeros((3, 3))

print("a) 1D Array of 8 Zeros:")
print(array1)

print("\nb) 4x4 Array of Ones:")
print(array2)

print("\nc) 3x3 Matrix of Zeros:")
print(array3)

a) 1D Array of 8 Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

b) 4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c) 3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
