<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

array1 = np.random.rand(10)

array2 = np.random.randn(3, 3)

array3 = np.random.randint(10, 51, (4, 5))

print("a) 1D Array of 10 Random Numbers (0 to 1):")
print(array1)

print("\nb) 3x3 Matrix of Random Numbers (Standard Normal Distribution):")
print(array2)

print("\nc) 4x5 Array of Random Integers (10 to 50):")
print(array3)


a) 1D Array of 10 Random Numbers (0 to 1):
[0.20545149 0.56460012 0.87128814 0.32099315 0.65843988 0.52936391
 0.37351659 0.17952453 0.35882    0.29434062]

b) 3x3 Matrix of Random Numbers (Standard Normal Distribution):
[[ 0.54713144 -0.28950276 -0.02729923]
 [-0.37066057 -0.68458301 -0.22085483]
 [ 1.14233634 -0.73445927  0.93666991]]

c) 4x5 Array of Random Integers (10 to 50):
[[13 12 41 11 38]
 [45 24 10 38 19]
 [19 13 10 31 38]
 [42 28 45 12 37]]
