<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

array = np.random.randint(1, 101, (4, 4))

print("4x4 Random Integer Matrix:")
print(array)

print("\nShape:", array.shape)
print("Dimension (ndim):", array.ndim)
print("Total Number of Elements (size):", array.size)
print("Data Type:", array.dtype)
print("Minimum Value:", array.min())
print("Maximum Value:", array.max())

4x4 Random Integer Matrix:
[[20 97 89 38]
 [87 56 72 99]
 [42 40 22 66]
 [41 83 10 96]]

Shape: (4, 4)
Dimension (ndim): 2
Total Number of Elements (size): 16
Data Type: int64
Minimum Value: 10
Maximum Value: 99
