<a href="https://colab.research.google.com/github/ishwaridhage10-cpu/NumPy-Project/blob/main/Q9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

array = np.random.randint(1, 51, 20)

matrix = array.reshape(4, 5)

print("4x5 Matrix:")
print(matrix)

print("\nSum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

print("\nMaximum Value in Each Row:")
print(np.max(matrix, axis=1))

4x5 Matrix:
[[ 1 30 39 25  1]
 [48 20 34 35  8]
 [43 17 43 16  6]
 [18 36 25  1 15]]

Sum: 461
Mean: 23.05
Standard Deviation: 14.698554350683606

Maximum Value in Each Row:
[39 48 43 36]
